@PDFValidationUnpublished   @PDFValidationUnpublished  @Regression_PreLogin @UAT_Regression @PREPROD_Regression @Regression
Feature:PDF Validation Unpublished

  Scenario Outline:PDF Validation Unpublished "<TestcaseNumber>" : "<pdfLink>"
    Given Open the PDF Link for "<TestcaseNumber>" as "<pdfLink>"
    Examples:
      | TestcaseNumber | pdfLink                                                                                                        |
      | Test1            | media/pdf/new-customer-application-form.pdf?                       |
      | Test2            | media/pdf/deposit-account-app-form.pdf?                            |
      | Test3            | media/pdf/prizebonds_gift_application_form.pdf?                    |
      | Test4            | media/pdf/new-customer-application-form-irish.pdf                  |
      | Test5            | media/pdf/prizebonds_gift_application_form_irish.pdf?              |
      | Test6            | media/pdf/deposit-account-app-form_irish.pdf?                      |
      | Test7            | media/pdf/statesavings-terms-conditions?                           |
      | Test8            | media/pdf/savings-bonds-specificconditions.pdf?                    |
      | Test9            | media/pdf/saving-cert-specific-conditions.pdf?                     |
      | Test11           | media/pdf/nsb-repaymentform-1-4.pdf?                               |
      | Test12           | media/pdf/nsbrepaymentformissue5.pdf?                              |
      | Test13           | media/pdf/ss_statementrequestform.pdf?                             |
      | Test14           | media/pdf/changeofaddressforsavingsandinvestment.pdf?              |
      | Test15           | media/pdf/statesavings-terms-conditions-irish?                     |
      | Test16           | media/pdf/sav_bonds_sp_cond_irish.pdf?                             |
      | Test17           | media/pdf/sav_certs_sp_cond_irish.pdf?                             |
      | Test18           | media/pdf/specific_cond_10year_irish.pdf?                          |
      | Test19           | media/pdf/othr_savingsrepaymentform_irish.pdf?                     |
      | Test20           | media/pdf/certbondsrepaymentform_irish.pdf?                        |
      | Test21           | media/pdf/cs_changenameaddr_irish.pdf?                             |
      | Test22           | media/pdf/deposit-account-brochure.pdf?                            |
      | Test23           | media/pdf/cs-loststolendepositbookform.pdf?                        |
      | Test25           | media/pdf/ss_statementrequestform.pdf?                             |
      | Test26           | media/pdf/changeofaddressforsavingsandinvestment.pdf?              |
      | Test27           | media/pdf/deletion-of-name-deposit-account-12-2017.pdf?            |
      | Test28           | media/pdf/dormancy-reactivation-form?                              |
      | Test29           | media/pdf/csadditionof-name-deposit-account-10-2017.pdf?           |
      | Test30           | media/pdf/ordinary_depositaccountrepayment_form.pdf?               |
      | Test31           | media/pdf/deposit-account-brochure_irish.pdf?                      |
      | Test32           | media/pdf/loststolenbook_irish.pdf?                                |
      | Test33           | media/pdf/cs_changenameaddr_irish.pdf?                             |
      | Test34           | media/pdf/dormancy_reactivationform_irish.pdf?                     |
      | Test35           | media/pdf/ordinarydepacctrepay_irish.pdf?                          |
      | Test36           | media/pdf/deposit-account-app-form_irish.pdf?                      |
      | Test37           | media/pdf/instalment-savings-specificconditions.pdf?               |
      | Test38           | media/pdf/nsb-repaymentform-1-4.pdf?                               |
      | Test39           | media/pdf/ss_statementrequestform.pdf?                             |
      | Test40           | media/pdf/instalment-savings-directdebit-mandate.pdf?              |
      | Test41           | media/pdf/changeofaddressforsavingsandinvestment.pdf?              |
      | Test42           | media/pdf/nis_sp_cond_irish.pdf?                                   |
      | Test43           | media/pdf/othr_savingsrepaymentform_irish.pdf?                     |
      | Test44           | media/pdf/instalment-savings-directdebit-mandate-irish.pdf?        |
      | Test45           | media/pdf/cs_changenameaddr_irish.pdf?                             |
      | Test46           | media/pdf/statesavings-terms-conditions?                           |
      | Test47           | media/pdf/savings-bonds-specificconditions.pdf?                    |
      | Test48           | media/pdf/saving-cert-specific-conditions.pdf?                     |
      | Test49           | media/pdf/nsb-10year-specificconditions.pdf?                       |
      | Test50           | media/pdf/instalment-savings-specificconditions.pdf?               |
      | Test51           | media/pdf/prizebonds_termsandconditions.pdf?                       |
      | Test52           | media/pdf/statesavings-terms-conditions-irish?                     |
      | Test53           | media/pdf/sav_bonds_sp_cond_irish.pdf?                             |
      | Test54           | media/pdf/sav_certs_sp_cond_irish.pdf?                             |
      | Test55           | media/pdf/specific_cond_10year_irish.pdf?ext=.                     |
      | Test56           | media/pdf/nis_sp_cond_irish.pdf?                                   |
      | Test57           | media/pdf/pb_sp_cond_irish.pdf?                                    |
      | Test58           | media/pdf/nsb-repaymentform-1-4.pdf?                               |
      | Test59           | media/pdf/nsbrepaymentformissue5.pdf?                              |
      | Test60           | media/pdf/prizebonds_repayment_form.pdf?                           |
      | Test61           | media/pdf/ordinary_depositaccountrepayment_form.pdf?               |
      | Test62           | media/pdf/othr_savingsrepaymentform_irish.pdf?                     |
      | Test63           | media/pdf/certbondsrepaymentform_irish.pdf?                        |
      | Test64           | media/pdf/prizebonds_repayment_form_irish.pdf?                     |
      | Test65           | media/pdf/ordinarydepacctrepay_irish.pdf?                          |
      | Test66           | media/pdf/notificationofdeath.pdf?                                 |
      | Test67           | media/pdf/deceased-information.pdf?                                |
      | Test68           | media/pdf/statesavings_customer_complaintform.pdf?ext=.            |
      | Test69           | media/pdf/prizebonds_customer_complaintform.pdf?ext=.              |
      | Test70           | media/pdf/t2651-19-statesavings_customer_complaintfor-ga.pdf?ext=. |
      | Test71           | media/pdf/t2651-19-prizebonds_customer_complaintfor-ga.pdf?ext=.   |
      | Test72           | media/pdf/change-of-mobile-number-form.pdf?ext=.                   |
      | Test73           | media/pdf/changeofaddressforsavingsandinvestment.pdf?ext=.         |
      | Test74           | media/pdf/changename_or_addressform.pdf?ext=.                      |
      | Test75           | media/pdf/deletion-of-name-deposit-account-12-2017.pdf?ext=.       |
      | Test76           | media/pdf/pb-_apptransferbonds_2017.pdf?ext=.                      |
      | Test77           | media/pdf/dormancy-reactivation-form?ext=.                         |
      | Test78           | media/pdf/csadditionof-name-deposit-account-10-2017.pdf?ext=.      |
      | Test79           | media/pdf/cs_changenameaddr_irish.pdf?                             |
      | Test80           | media/pdf/dormancy_reactivationform_irish.pdf?                     |
      | Test81           | media/pdf/new-customer-brochure.pdf?ext=.pdf                       |
      | Test82           | media/pdf/deposit-account-brochure.pdf?ext=.                       |
      | Test83           | media/pdf/prizebonds_gift_brochure.pdf?ext=.                       |
      | Test84           | media/pdf/summary-of-products.pdf?ext=.                            |
      | Test85           | media/pdf/deposit-account-brochure_irish.pdf?ext=.                 |
      | Test86           | media/pdf/new-customer-brochure-irish.pdf?ext=.pdf                 |
      | Test87           | media/pdf/prizebonds_gift_brochure_irish.pdf?ext=.                 |
      | Test88           | media/pdf/summary-of-products-irish.pdf?ext=.                      |
      | Test89           | media/pdf/a4-dormancy-bilingual-customer-notice.pdf?ext=.          |
      | Test90           | media/pdf/ss_statementrequestform.pdf?ext=.                        |
      | Test91           | media/pdf/instalment-savings-directdebit-mandate.pdf?ext=.         |
      | Test92           | media/pdf/non_resident_declaration_form.pdf?ext=.                  |
      | Test93           | media/pdf/prizebonds_directdebit_mandate.pdf?ext=.                 |
      | Test94           | media/pdf/dormancy-reactivation-form?ext=.                         |
      | Test95           | media/pdf/prizebonds_direct_debit_mandate_irish.pdf?               |
      | Test96           | media/pdf/instalment-savings-directdebit-mandate-irish.pdf?        |
      | Test97           | media/pdf/dormancy_reactivationform_irish.pdf?                     |